[book]
authors = ["HitBlast"]
language = "en"
multilingual = false
src = "src"
title = "IgKnite"

[output.html]
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/IgKniteDev/IgKnite"